/* Generated by MyraPad at 2/1/2025 5:58:27 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace AbarimMUD.MapEditor.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			_menuItemFileOpen = new MenuItem();
			_menuItemFileOpen.Text = "&Open";
			_menuItemFileOpen.ShortcutText = "Ctrl+O";
			_menuItemFileOpen.Id = "_menuItemFileOpen";

			_menuItemFileSave = new MenuItem();
			_menuItemFileSave.Text = "&Save";
			_menuItemFileSave.ShortcutText = "Ctrl+S";
			_menuItemFileSave.Id = "_menuItemFileSave";

			_menuItemFileSaveAs = new MenuItem();
			_menuItemFileSaveAs.Text = "S&ave As...";
			_menuItemFileSaveAs.Id = "_menuItemFileSaveAs";

			var menuItem1 = new MenuItem();
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemFileOpen);
			menuItem1.Items.Add(_menuItemFileSave);
			menuItem1.Items.Add(_menuItemFileSaveAs);

			_menuHelpAbout = new MenuItem();
			_menuHelpAbout.Text = "&About";
			_menuHelpAbout.Id = "_menuHelpAbout";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "&Help";
			menuItem2.Items.Add(_menuHelpAbout);

			_mainMenu = new HorizontalMenu();
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(menuItem1);
			_mainMenu.Items.Add(menuItem2);

			_labelStatus = new Label();
			_labelStatus.Text = "Status";
			_labelStatus.TextColor = ColorStorage.CreateColor(3, 121, 255, 255);
			_labelStatus.Id = "_labelStatus";

			var label1 = new Label();
			label1.Text = "Midgaard.json";

			_listAreas = new ListView();
			_listAreas.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listAreas.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listAreas.Id = "_listAreas";
			_listAreas.Widgets.Add(label1);

			_panelMap = new ScrollViewer();
			_panelMap.Id = "_panelMap";

			_labelRoomsCount = new Label();
			_labelRoomsCount.Text = "Rooms: 10";
			_labelRoomsCount.TextColor = ColorStorage.CreateColor(3, 121, 255, 255);
			_labelRoomsCount.Id = "_labelRoomsCount";

			_labelGridSize = new Label();
			_labelGridSize.Text = "Grid Size: 10x10";
			_labelGridSize.TextColor = ColorStorage.CreateColor(3, 121, 255, 255);
			_labelGridSize.Id = "_labelGridSize";

			_panelConnectionIssues = new VerticalStackPanel();
			_panelConnectionIssues.Spacing = 8;
			_panelConnectionIssues.Id = "_panelConnectionIssues";
			_panelConnectionIssues.Widgets.Add(_labelRoomsCount);
			_panelConnectionIssues.Widgets.Add(_labelGridSize);

			var panel1 = new Panel();
			panel1.Widgets.Add(_panelMap);
			panel1.Widgets.Add(_panelConnectionIssues);

			var tabItem1 = new TabItem();
			tabItem1.Text = "Map";
			tabItem1.Content = panel1;

			var label2 = new Label();
			label2.Text = "a rat";

			_listMobiles = new ListView();
			_listMobiles.Id = "_listMobiles";
			_listMobiles.Widgets.Add(label2);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Widgets.Add(_listMobiles);

			var tabItem2 = new TabItem();
			tabItem2.Text = "Mobiles";
			tabItem2.Content = horizontalStackPanel1;

			var tabControl1 = new TabControl();
			tabControl1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			tabControl1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			tabControl1.Items.Add(tabItem1);
			tabControl1.Items.Add(tabItem2);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			StackPanel.SetProportionType(_topSplitPane, Myra.Graphics2D.UI.ProportionType.Fill);
			_topSplitPane.Widgets.Add(_listAreas);
			_topSplitPane.Widgets.Add(tabControl1);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_mainMenu);
			verticalStackPanel1.Widgets.Add(_labelStatus);
			verticalStackPanel1.Widgets.Add(_topSplitPane);

			
			Widgets.Add(verticalStackPanel1);
		}

		
		public MenuItem _menuItemFileOpen;
		public MenuItem _menuItemFileSave;
		public MenuItem _menuItemFileSaveAs;
		public MenuItem _menuHelpAbout;
		public HorizontalMenu _mainMenu;
		public Label _labelStatus;
		public ListView _listAreas;
		public ScrollViewer _panelMap;
		public Label _labelRoomsCount;
		public Label _labelGridSize;
		public VerticalStackPanel _panelConnectionIssues;
		public ListView _listMobiles;
		public HorizontalSplitPane _topSplitPane;
	}
}
